version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
  pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
  dev-environment:
    build: .
    depends_on:
      - postgres

volumes:
  postgres-data: